// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8k6gozN2RbrW0Ujmdx2mXGiWD1WXyxso',
    appId: '1:223147521233:web:ba205394599bb99ded81f0',
    messagingSenderId: '223147521233',
    projectId: 'chat-app-a493d',
    authDomain: 'chat-app-a493d.firebaseapp.com',
    storageBucket: 'chat-app-a493d.appspot.com',
    measurementId: 'G-7GJ7P796ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-FkrCZ316J_sZd8LjbPXibiDhIQlSuDY',
    appId: '1:223147521233:android:cb2971b55f30f8e4ed81f0',
    messagingSenderId: '223147521233',
    projectId: 'chat-app-a493d',
    storageBucket: 'chat-app-a493d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1cuiTL0cIq5nKFdXALUbqTmQ3f94WE2Q',
    appId: '1:223147521233:ios:b5b95769994b9c55ed81f0',
    messagingSenderId: '223147521233',
    projectId: 'chat-app-a493d',
    storageBucket: 'chat-app-a493d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1cuiTL0cIq5nKFdXALUbqTmQ3f94WE2Q',
    appId: '1:223147521233:ios:b5b95769994b9c55ed81f0',
    messagingSenderId: '223147521233',
    projectId: 'chat-app-a493d',
    storageBucket: 'chat-app-a493d.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8k6gozN2RbrW0Ujmdx2mXGiWD1WXyxso',
    appId: '1:223147521233:web:7480c014548811beed81f0',
    messagingSenderId: '223147521233',
    projectId: 'chat-app-a493d',
    authDomain: 'chat-app-a493d.firebaseapp.com',
    storageBucket: 'chat-app-a493d.appspot.com',
    measurementId: 'G-6WJ4V9HDKS',
  );

}